### ISSUE TITLE
Novice Question about this cool project!

### ISSUE THREAD

**Issue by solvingj** [fpm-within-docker/fpm-within-docker#2]
I'm a bit new to docker, so I apologize if this is a novice question.  However, I think I know enough to get this working, and this bit from the readme was confusing to me: 

> First, a build-image is constructed via docker. 

This statement indicates that the build-image is constructed automatically somehow.  However, from the sentences that come after it, I now believe this is something the user needs to do themselves: manually construct a custom build image which inherits from the existing image(s).   Is this correct? 

Could you perhaps provide some clarity around this part of the process for novices like myself? 

Thanks for making this project!

**Comment by alanfranz** [comment]
Take a look at the example project (and try running it as well). The build file https://github.com/alanfranz/fpm-within-docker/blob/master/example-project/packaging/ubuntu-trusty/build is completely commented, and I recommend copying the packaging directory in order to start a new packaging project.

Most of the times you'll need to inherit from the fpm-within-docker build image, adding your build dependencies.

**Comment by solvingj** [comment]
Thanks, it looks like I still have some more fundamentals to learn to be able to use this.
